### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by tigerdi** [roblav96/nativescript-AFNetworking#1]
Hi

Just a simple question really regarding the setup of this plugin. After it has been installed, how to I get access to the AFNetworking classes etc? Shouldnt they become available without doing anything? I dont think I need to import a module do I?

It would be great if you could add a bit of information on the Readme. 

Thanks

**Comment by roblav96** [comment]
@tigerdi This shouldn't be a public repo lol but here's the API https://gist.github.com/roblav96/e38ec6312b14ec9aff9c10b85c833ff9

**Comment by tigerdi** [comment]
Thats great - thanks very much!
